// <auto-generated />
namespace SciEvidenceBank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addResearchFields2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addResearchFields2));
        
        string IMigrationMetadata.Id
        {
            get { return "202511230150226_addResearchFields2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
